### ISSUE TITLE
基于stage分支运行出现错误，请教大佬如何自己制作

### ISSUE THREAD

**Issue by ShevonKuan** [toraidl/coloros_port_kebab#2]
基于ubuntu使用了stage分支的https://github.com/toraidl/coloros_port_kebab/commit/059eff8274367919210d5963e9f0048e3ae1d419 来运行，出现报错
```
[1222/150222.349963:INFO:erofs_filesystem.cc(205)] Using compression algo Algo {type: LZ4HC, level: 9} for out/target/product/OnePlus8T/IMAGES/vendor.img
~/coloros_port_kebab-staging/otatools ~/coloros_port_kebab-staging
2024-12-22 15:02:22 - common.py - WARNING : Failed to read SYSTEM/etc/build.prop
2024-12-22 15:02:22 - common.py - WARNING : Failed to read VENDOR/etc/build.prop
2024-12-22 15:02:22 - common.py - WARNING : Failed to read PRODUCT/etc/build.prop
2024-12-22 15:02:22 - common.py - WARNING : Failed to read SYSTEM_EXT/etc/build.prop
2024-12-22 15:02:22 - common.py - WARNING : Failed to read ODM/etc/build.prop
2024-12-22 15:02:22 - common.py - WARNING : Failed to read VENDOR_DLKM/etc/build.prop
2024-12-22 15:02:22 - common.py - WARNING : Failed to read VENDOR_DLKM/build.prop
2024-12-22 15:02:22 - common.py - WARNING : Failed to read build.prop for partition vendor_dlkm
2024-12-22 15:02:22 - common.py - WARNING : Failed to read ODM_DLKM/etc/build.prop
2024-12-22 15:02:22 - common.py - WARNING : Failed to read ODM_DLKM/build.prop
2024-12-22 15:02:22 - common.py - WARNING : Failed to read build.prop for partition odm_dlkm
2024-12-22 15:02:22 - common.py - WARNING : Failed to read SYSTEM_DLKM/etc/build.prop
2024-12-22 15:02:22 - common.py - WARNING : Failed to read SYSTEM_DLKM/build.prop
2024-12-22 15:02:22 - common.py - WARNING : Failed to read build.prop for partition system_dlkm
2024-12-22 15:02:22 - common.py - INFO    :   Running: "/root/coloros_port_kebab-staging/otatools/bin/unpack_bootimg --boot_img /root/coloros_port_kebab-staging/out/target/product/OnePlus8T/IMAGES/boot.img --out /tmp/boot_lsm_16rv.img"
2024-12-22 15:02:22 - common.py - INFO    : boot magic: ANDROID!
kernel_size: 47511568
kernel load address: 0x00008000
ramdisk size: 1522509
ramdisk load address: 0x01000000
second bootloader size: 0
second bootloader load address: 0x00000000
kernel tags load address: 0x00000100
page size: 4096
os version: 12.0.0
os patch level: 2024-08
boot image header version: 2
product name:
command line args: console=ttyMSM0,115200n8 earlycon=msm_geni_serial,0xa90000 androidboot.hardware=qcom androidboot.console=ttyMSM0 androidboot.memcg=1 lpm_levels.sleep_disabled=1 video=vfb:640x400,bpp=32,memsize=3072000 msm_rtb.filter=0x237 service_locator.enable=1 androidboot.usbcontroller=a600000.dwc3 swiotlb=2048 loop.max_part=7 cgroup.memory=nokmem,nosocket reboot=panic_warm kpti=off buildvariant=user androidboot.vbmeta.device_state=unlocked
additional command line args:
recovery dtbo size: 0
recovery dtbo offset: 0x0000000000000000
boot header size: 1660
dtb size: 11028247
dtb address: 0x0000000001f00000
2024-12-22 15:02:22 - common.py - INFO    :   Running: "gzip -d"
2024-12-22 15:02:22 - common.py - INFO    :   Running: "/root/coloros_port_kebab-staging/otatools/bin/toybox cpio -F /tmp/boot_lsm_16rv.img/uncompressed_ramdisk -i"
2024-12-22 15:02:22 - common.py - INFO    :
2024-12-22 15:02:22 - common.py - WARNING : Unable to get boot image timestamp: no system/etc/ramdisk/build.prop in ramdisk
2024-12-22 15:02:22 - common.py - WARNING : Failed to read IMAGES/init_boot.img
2024-12-22 15:02:22 - ota_from_target_files.py - INFO    : --- target info ---
2024-12-22 15:02:22 - common.py - INFO    : ab_partitions             = (list) ['abl', 'aop', 'bluetooth', 'boot', 'cmnlib', 'cmnlib64', 'devcfg', 'dsp', 'dtbo', 'featenabler', 'hyp', 'imagefv', 'keymaster', 'logo', 'mdm_oem_stanvbk', 'modem', 'multiimgoem', 'my_bigball', 'my_carrier', 'my_company', 'my_engineering', 'my_heytap', 'my_manifest', 'my_preload', 'my_product', 'my_region', 'my_stock', 'odm', 'oem_cust1', 'product', 'qupfw', 'recovery', 'reserve', 'spunvm', 'storsec', 'system', 'system_ext', 'tz', 'uefisecapp', 'vbmeta', 'vbmeta_system', 'vendor', 'xbl', 'xbl_config', 'xbl_config_lp5', 'xbl_lp5', '']
2024-12-22 15:02:22 - common.py - INFO    : ab_update                 = (str) true
2024-12-22 15:02:22 - common.py - INFO    : boot.build.prop           = (PartitionBuildProps) <common.PartitionBuildProps object at 0x7ff99f8b2e10>
2024-12-22 15:02:22 - common.py - INFO    : build.prop                = (PartitionBuildProps) <common.PartitionBuildProps object at 0x7ff99f5d5ad0>
2024-12-22 15:02:22 - common.py - INFO    : fstab                     = (NoneType) None
2024-12-22 15:02:22 - common.py - INFO    : fstab_version             = (int) 2
2024-12-22 15:02:22 - common.py - INFO    : init_boot.build.prop      = (PartitionBuildProps) <common.PartitionBuildProps object at 0x7ff99f6108d0>
2024-12-22 15:02:22 - common.py - INFO    : odm.build.prop            = (PartitionBuildProps) <common.PartitionBuildProps object at 0x7ff99f60b250>
2024-12-22 15:02:22 - common.py - INFO    : odm_dlkm.build.prop       = (PartitionBuildProps) <common.PartitionBuildProps object at 0x7ff99f610390>
2024-12-22 15:02:22 - common.py - INFO    : product.build.prop        = (PartitionBuildProps) <common.PartitionBuildProps object at 0x7ff99f608950>
2024-12-22 15:02:22 - common.py - INFO    : recovery_api_version      = (int) 3
2024-12-22 15:02:22 - common.py - INFO    : system.build.prop         = (PartitionBuildProps) <common.PartitionBuildProps object at 0x7ff99f5d5ad0>
2024-12-22 15:02:22 - common.py - INFO    : system_dlkm.build.prop    = (PartitionBuildProps) <common.PartitionBuildProps object at 0x7ff99f610410>
2024-12-22 15:02:22 - common.py - INFO    : system_ext.build.prop     = (PartitionBuildProps) <common.PartitionBuildProps object at 0x7ff99f608a10>
2024-12-22 15:02:22 - common.py - INFO    : vendor.build.prop         = (PartitionBuildProps) <common.PartitionBuildProps object at 0x7ff99f714190>
2024-12-22 15:02:22 - common.py - INFO    : vendor_dlkm.build.prop    = (PartitionBuildProps) <common.PartitionBuildProps object at 0x7ff99f60b210>
2024-12-22 15:02:22 - common.py - INFO    :   Running: "openssl pkcs8 -in build/make/target/product/security/testkey.pk8 -inform DER -nocrypt"
2024-12-22 15:02:22 - common.py - INFO    :   Running: "openssl pkcs8 -in build/make/target/product/security/testkey.pk8 -inform DER -passin pass:"
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/root/coloros_port_kebab-staging/otatools/bin/ota_from_target_files/__main__.py", line 12, in <module>
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "ota_from_target_files.py", line 1548, in <module>
  File "ota_from_target_files.py", line 1479, in main
common.ExternalError: Private key build/make/target/product/security/testkey.pk8 doesn't exist. Make sure you passed the correct key path through -k option
~/coloros_port_kebab-staging
md5sum: out/OnePlus8T-ota_full-11_C.61-user-15.0.zip: No such file or directory
mv: cannot stat 'out/OnePlus8T-ota_full-11_C.61-user-15.0.zip': No such file or directory
```

- python 3.12.3 
- openjdk-17-jre（jdk-8无法运行）

**Comment by ShevonKuan** [comment]
@toraidl 大佬我花了不少时间去定位错误，但是依然解决不了，恳请大佬指导

**Comment by toraidl** [comment]
> @toraidl 大佬我花了不少时间去定位错误，但是依然解决不了，恳请大佬指导

https://github.com/toraidl/coloros_port_kebab/blob/1d212cad3a05befedb2e49e0431a584439341bd5/port.sh#L1024 

取消这行的注释。

**Comment by toraidl** [comment]
默认是采用的otatools/build/make/target/product/security 下面的testkey签名
刚刚发现 build目录被添加到了ignore文件。 我重新更新下。

**Comment by ShevonKuan** [comment]
十分感谢大佬，我试试。
（还有一个小问题，不过写在这个issue不太合适，就是感觉从应用里面上滑回桌面会出现一个半秒的卡顿，不知道为什么，用的是123网盘上大佬的包）

**Comment by toraidl** [comment]
> 十分感谢大佬，我试试。 （还有一个小问题，不过写在这个issue不太合适，就是感觉从应用里面上滑回桌面会出现一个半秒的卡顿，不知道为什么，用的是123网盘上大佬的包）

毕竟不是官方，有问题也是很正常
